# Generated by Django 5.1.4 on 2025-01-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpsychologist',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
