# Generated by Django 5.1 on 2024-08-11 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cedula_profesional', models.CharField(blank=True, max_length=255, null=True)),
                ('instituto', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('psicologo', 'Psicologo'), ('admin', 'Admin'), ('administrador del instituto', 'Administrador del Instituto')], max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_pacientes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_completo', models.CharField(blank=True, default='Nombre Desconocido', max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, default=0, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], default='otro', max_length=10, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], default='soltero', max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, default='default@example.com', max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('acude_voluntariamente', models.BooleanField(default=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_padre', models.IntegerField(blank=True, default=0, null=True)),
                ('escolaridad_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_patologicos_padre', models.TextField(blank=True, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('edad_madre', models.IntegerField(blank=True, default=0, null=True)),
                ('escolaridad_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_patologicos_madre', models.TextField(blank=True, null=True)),
                ('estado_civil_padres', models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], default='soltero', max_length=50, null=True)),
                ('nombre_hermano_1', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_hermano_1', models.TextField(blank=True, null=True)),
                ('edad_hermano_1', models.IntegerField(blank=True, default=0, null=True)),
                ('grado_escolar_hermano_1', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_patologicos_hermano_1', models.TextField(blank=True, null=True)),
                ('adicciones_hermano_1', models.TextField(blank=True, null=True)),
                ('nombre_hermano_2', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_hermano_2', models.TextField(blank=True, null=True)),
                ('edad_hermano_2', models.IntegerField(blank=True, default=0, null=True)),
                ('grado_escolar_hermano_2', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_patologicos_hermano_2', models.TextField(blank=True, null=True)),
                ('adicciones_hermano_2', models.TextField(blank=True, null=True)),
                ('nombre_hermano_3', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_hermano_3', models.TextField(blank=True, null=True)),
                ('edad_hermano_3', models.IntegerField(blank=True, default=0, null=True)),
                ('grado_escolar_hermano_3', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedentes_patologicos_hermano_3', models.TextField(blank=True, null=True)),
                ('adicciones_hermano_3', models.TextField(blank=True, null=True)),
                ('otras_personas_hogar', models.TextField(blank=True, null=True)),
                ('asma_alergias', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('catarros_frecuentes', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('epilepsia_convulsiones', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('convulsiones_febriles', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('manias', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('lesiones_cabeza', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('cirugias_hospitalizacion', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('problemas_vision', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
                ('problemas_apetito', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('pasado', 'Pasado'), ('presente', 'Presente')], default='nunca', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='manuscritos/')),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paciente')),
            ],
        ),
    ]
