# Generated by Django 5.1 on 2024-08-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='usuario',
            new_name='email',
        ),
    ]
