# Generated by Django 5.1 on 2024-08-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_usuario_cita_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paciente",
            name="adicciones_hermano_1",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="adicciones_hermano_2",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="adicciones_hermano_3",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_hermano_1",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_hermano_2",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_hermano_3",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_patologicos_hermano_1",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_patologicos_hermano_2",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_patologicos_hermano_3",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_patologicos_madre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="antecedentes_patologicos_padre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="asma_alergias",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="catarros_frecuentes",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="cirugias_hospitalizacion",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="convulsiones_febriles",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="edad_hermano_1",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="edad_hermano_2",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="edad_hermano_3",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="edad_madre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="edad_padre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="epilepsia_convulsiones",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="escolaridad_madre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="escolaridad_padre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="estado_civil_padres",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="grado_escolar_hermano_1",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="grado_escolar_hermano_2",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="grado_escolar_hermano_3",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="lesiones_cabeza",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="manias",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="nombre_hermano_1",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="nombre_hermano_2",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="nombre_hermano_3",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="nombre_madre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="nombre_padre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="ocupacion_madre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="ocupacion_padre",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="otras_personas_hogar",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="problemas_apetito",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="problemas_vision",
        ),
        migrations.CreateModel(
            name="Hermano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("antecedentes", models.TextField(blank=True, null=True)),
                ("edad", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "grado_escolar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("antecedentes_patologicos", models.TextField(blank=True, null=True)),
                ("adicciones", models.TextField(blank=True, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hermanos",
                        to="dashboard.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hogar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otras_personas", models.TextField(blank=True, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hogar",
                        to="dashboard.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Padres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_padre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("edad_padre", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "escolaridad_padre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ocupacion_padre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "antecedentes_patologicos_padre",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "nombre_madre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("edad_madre", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "escolaridad_madre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ocupacion_madre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "antecedentes_patologicos_madre",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "estado_civil_padres",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soltero", "Soltero"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viudo", "Viudo"),
                        ],
                        default="soltero",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="padres",
                        to="dashboard.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asma_alergias",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "catarros_frecuentes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "epilepsia_convulsiones",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "convulsiones_febriles",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "manias",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "lesiones_cabeza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cirugias_hospitalizacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "problemas_vision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "problemas_apetito",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nunca", "Nunca"),
                            ("pasado", "Pasado"),
                            ("presente", "Presente"),
                        ],
                        default="nunca",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salud",
                        to="dashboard.paciente",
                    ),
                ),
            ],
        ),
    ]
