# Generated by Django 5.1 on 2024-08-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_paciente_adicciones_hermano_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hermano",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padres",
            name="fecha_nacimiento_madre",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="padres",
            name="fecha_nacimiento_padre",
            field=models.DateField(blank=True, null=True),
        ),
    ]
